--- #YAML:1.0
name:                WWW-Lengthen
version:             0.01
abstract:            lengthen 'shortened' urls
license:             perl
author:              
    - Kenichi Ishigaki <ishigaki@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    LWP::UserAgent:                0
    Test::More:                    0.47
    Test::UseAllModules:           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
